# Generated by Django 3.1.1 on 2020-09-06 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 9, 6, 9, 37, 20, 884760), verbose_name='Дата создания')),
                ('name', models.CharField(max_length=200, verbose_name='Название объявления')),
                ('price', models.IntegerField(verbose_name='Цена (в копейках)')),
                ('main_photo', models.TextField(verbose_name='Ссылка на изображение')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(verbose_name='Ссылка на изображение')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalimages', to='main.bulletin', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
