# Generated by Django 3.1 on 2020-09-06 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 9, 6, 15, 16, 43, 766179), verbose_name='Date of creation')),
                ('name', models.CharField(max_length=200, verbose_name='Bulletin name')),
                ('price', models.PositiveIntegerField(verbose_name='Price (cents)')),
                ('main_photo', models.URLField(verbose_name='Hyperlink to image')),
                ('description', models.TextField(max_length=1000, verbose_name='Bulletin description')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Hyperlink to main image')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalimages', to='api.bulletin', verbose_name='Bulletin')),
            ],
            options={
                'verbose_name': 'Additional image',
                'verbose_name_plural': 'Additional images',
            },
        ),
    ]
